### ISSUE TITLE
Add Chaldean Cipher to calc/ciphers-extra.js

### ISSUE THREAD

**Issue by ghost** [gematro/gematro.github.io#4]
It was added and eventually removed according to pull request #2 

Cipher: `https://i.imgur.com/6wKTCpF.png`

Yes, I know that you can add your own ciphers. 👍🏻 Thanks for your hard work, and decode your reality.

**Comment by gematro** [comment]
"Chaldean" cipher is actually a system devised by Cheiro (an Irish astrologer and occultist of the early 20th century), so I renamed it to "Cheiro Numerology". It is available inside "Other" category in the main cipher menu.
